# Generated by Django 4.2.6 on 2023-11-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_addmovies'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmovies',
            name='banner',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='addmovies',
            name='censor',
            field=models.CharField(default='D', max_length=25),
        ),
        migrations.AddField(
            model_name='addmovies',
            name='joner1',
            field=models.CharField(default='A', max_length=50),
        ),
        migrations.AddField(
            model_name='addmovies',
            name='joner2',
            field=models.CharField(default='B', max_length=50),
        ),
        migrations.AddField(
            model_name='addmovies',
            name='joner3',
            field=models.CharField(default='C', max_length=50),
        ),
        migrations.AddField(
            model_name='addmovies',
            name='language',
            field=models.CharField(default='LANGUAGE', max_length=50),
        ),
        migrations.AddField(
            model_name='addmovies',
            name='movieFromat',
            field=models.CharField(default='Format', max_length=20),
        ),
        migrations.AddField(
            model_name='addmovies',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='addmovies',
            name='releasingDate',
            field=models.CharField(default='Date', max_length=20),
        ),
        migrations.AddField(
            model_name='addmovies',
            name='scrolliimg2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='addmovies',
            name='scrollimg1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
