# Generated by Django 4.2.6 on 2023-11-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_addmovies_banner_addmovies_censor_addmovies_joner1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmovies',
            old_name='scrolliimg2',
            new_name='actor_img1',
        ),
        migrations.RenameField(
            model_name='addmovies',
            old_name='scrollimg1',
            new_name='actor_img2',
        ),
        migrations.AddField(
            model_name='addmovies',
            name='actor_Name1',
            field=models.CharField(default='Name', max_length=50),
        ),
        migrations.AddField(
            model_name='addmovies',
            name='actor_Name2',
            field=models.CharField(default='Name', max_length=50),
        ),
        migrations.AddField(
            model_name='addmovies',
            name='actor_Name3',
            field=models.CharField(default='Name', max_length=50),
        ),
        migrations.AddField(
            model_name='addmovies',
            name='actor_Name4',
            field=models.CharField(default='Name', max_length=50),
        ),
        migrations.AddField(
            model_name='addmovies',
            name='actor_img3',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='addmovies',
            name='actor_img4',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
