# Generated by Django 4.2.6 on 2023-11-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_rename_scrolliimg2_addmovies_actor_img1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmovies',
            name='duration',
            field=models.CharField(default='Duration', max_length=10),
        ),
    ]
