# Generated by Django 4.2.6 on 2023-12-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0007_addmovies_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('seat', models.CharField(max_length=100)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
    ]
