# Generated by Django 4.2.6 on 2023-12-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0008_cartdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
