# Generated by Django 4.2.6 on 2023-12-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0009_cartdetails_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetails',
            name='day',
            field=models.CharField(default='day', max_length=20),
        ),
        migrations.AddField(
            model_name='cartdetails',
            name='show',
            field=models.CharField(default='show', max_length=20),
        ),
    ]
